
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xe1\t\xefJ\xe9\x93\xb0\xfen\xdb\x98\xb4\x93c\xb6\xc1'
    
_lr_action_items = {'RPAREN':([2,7,9,10,12,15,16,17,],[-1,12,-6,-3,-2,17,-4,-5,]),'NUMBER':([0,3,4,5,11,13,],[2,2,7,2,2,2,]),'LBRACKET':([0,3,4,5,11,13,],[3,3,3,3,3,3,]),'COMMA':([1,2,6,7,8,9,10,12,14,15,16,17,],[5,-1,11,-1,13,5,-3,-2,5,5,-4,-5,]),'LPAREN':([0,3,4,5,11,13,],[4,4,4,4,4,4,]),'RBRACKET':([2,6,9,10,12,14,16,17,],[-1,10,-6,-3,-2,16,-4,-5,]),'$end':([1,2,9,10,12,16,17,],[0,-1,-6,-3,-2,-4,-5,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'exp':([0,3,4,5,11,13,],[1,6,8,9,14,15,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> exp","S'",1,None,None,None),
  ('exp -> NUMBER','exp',1,'p_exp_number','C:\\Users\\Rejith\\workspace\\PythonTest\\com\\test\\tuple.py',44),
  ('exp -> LPAREN NUMBER RPAREN','exp',3,'p_exp_parens','C:\\Users\\Rejith\\workspace\\PythonTest\\com\\test\\tuple.py',48),
  ('exp -> LBRACKET exp RBRACKET','exp',3,'p_exp_num_bracket','C:\\Users\\Rejith\\workspace\\PythonTest\\com\\test\\tuple.py',53),
  ('exp -> LBRACKET exp COMMA exp RBRACKET','exp',5,'p_exp_brackets','C:\\Users\\Rejith\\workspace\\PythonTest\\com\\test\\tuple.py',57),
  ('exp -> LPAREN exp COMMA exp RPAREN','exp',5,'p_exp_tuple','C:\\Users\\Rejith\\workspace\\PythonTest\\com\\test\\tuple.py',61),
  ('exp -> exp COMMA exp','exp',3,'p_exp_comma','C:\\Users\\Rejith\\workspace\\PythonTest\\com\\test\\tuple.py',65),
]
